'use strict';
const fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'public');
function page(template,name,id,title){
  let html=fs.readFileSync(path.join(root,template),'utf8');
  html=html.replace(/data-page="[^"]+"/,'data-page="'+id+'"');
  if(title)html=html.replace(/<title>.*?<\/title>/,'<title>'+title+' · Retirement</title>');
  fs.writeFileSync(path.join(root,name),html);
}
for(const p of ['household','accounts','plan-settings','employment','properties','pensions','app-config'])page('config.html',p+'.html',p,p==='app-config'?'App Config':p[0].toUpperCase()+p.slice(1));
page('index.html','detailed.html','detailed','Plan details');
page('planning.html','scenarios.html','scenarios','Compare scenarios');
page('planning.html','withdrawals.html','withdrawals','Withdrawal strategy');
let withdrawals=fs.readFileSync(path.join(root,'withdrawals.html'),'utf8').replace('<h1>Compare scenarios</h1>','<h1>Withdrawal strategy</h1>').replace('Try a different retirement date, pension start or home. Your current plan stays separate until you apply a change.','Choose how to use your savings. Compare tax, benefits and final net worth before applying a withdrawal plan.');
fs.writeFileSync(path.join(root,'withdrawals.html'),withdrawals);
const source=['planning-core.js','engine.js','status-check.js'].map(f=>fs.readFileSync(path.join(root,f),'utf8')).join('\n');
fs.writeFileSync(path.join(root,'worker-bundle.js'),'// Generated by scripts/build-client.js. Do not edit.\nwindow.RetirementWorkerSource='+JSON.stringify(source)+';\n');
console.log('Built dedicated pages and offline calculation workers.');
